[project]
name = "test_validator"
version = "0.0.0"
description = "Template repo for Guardrails Hub validators."
authors = ["Guardrails AI <contact@guardrailsai.com>"]
license = {file = "LICENSE"}
readme = "README.md"
requires-python = ">= 3.8"
dependencies = [
    "rstr",
    "guardrails-ai>=0.3.2"
]